[package]
name = "swede-lsp"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[[bin]]
name = "swede-lsp"
path = "src/main.rs"

[dependencies]
swede-analysis = { workspace = true }
tower-lsp = "0.20"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
