#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 20
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 30

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_recipe = 2,
  anon_sym_menu = 3,
  sym_comment = 4,
  anon_sym_COLON = 5,
  sym_meta_value = 6,
  anon_sym_basis = 7,
  anon_sym_EQ = 8,
  anon_sym_COMMA = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LPAREN = 12,
  anon_sym_SEMI = 13,
  anon_sym_RPAREN = 14,
  anon_sym_BANG = 15,
  anon_sym_DOT = 16,
  anon_sym_LT_PLUS = 17,
  anon_sym_POUND = 18,
  anon_sym_GT = 19,
  anon_sym_SLASH = 20,
  anon_sym_DASH_GT = 21,
  sym_amount_text = 22,
  sym_temp = 23,
  sym_timer_active = 24,
  sym_timer_passive = 25,
  sym_timer_unbounded = 26,
  sym_string = 27,
  anon_sym_AMPby = 28,
  anon_sym_AMPduring = 29,
  anon_sym_AMPlag = 30,
  sym_duration = 31,
  sym_source_file = 32,
  sym_recipe = 33,
  sym_menu = 34,
  sym__statement = 35,
  sym_meta_line = 36,
  sym_basis_decl = 37,
  sym_binding = 38,
  sym_output_list = 39,
  sym_output = 40,
  sym__expr = 41,
  sym_call = 42,
  sym__arg_list = 43,
  sym_arg = 44,
  sym_equip_list = 45,
  sym_equip_item = 46,
  sym_equip = 47,
  sym_ingredient = 48,
  sym_node_ref = 49,
  sym_sub_ref = 50,
  sym_path = 51,
  sym_remap = 52,
  sym_mapping = 53,
  sym_amount = 54,
  sym_annotation = 55,
  sym_timer = 56,
  sym_flag = 57,
  sym_link = 58,
  sym_menu_stmt = 59,
  aux_sym_recipe_repeat1 = 60,
  aux_sym_menu_repeat1 = 61,
  aux_sym_binding_repeat1 = 62,
  aux_sym_output_list_repeat1 = 63,
  aux_sym__arg_list_repeat1 = 64,
  aux_sym_equip_list_repeat1 = 65,
  aux_sym_path_repeat1 = 66,
  aux_sym_remap_repeat1 = 67,
  aux_sym_menu_stmt_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_recipe] = "recipe",
  [anon_sym_menu] = "menu",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [sym_meta_value] = "meta_value",
  [anon_sym_basis] = "basis",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_SEMI] = ";",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_LT_PLUS] = "<+",
  [anon_sym_POUND] = "#",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH_GT] = "->",
  [sym_amount_text] = "amount_text",
  [sym_temp] = "temp",
  [sym_timer_active] = "timer_active",
  [sym_timer_passive] = "timer_passive",
  [sym_timer_unbounded] = "timer_unbounded",
  [sym_string] = "string",
  [anon_sym_AMPby] = "&by",
  [anon_sym_AMPduring] = "&during",
  [anon_sym_AMPlag] = "&lag",
  [sym_duration] = "duration",
  [sym_source_file] = "source_file",
  [sym_recipe] = "recipe",
  [sym_menu] = "menu",
  [sym__statement] = "_statement",
  [sym_meta_line] = "meta_line",
  [sym_basis_decl] = "basis_decl",
  [sym_binding] = "binding",
  [sym_output_list] = "output_list",
  [sym_output] = "output",
  [sym__expr] = "_expr",
  [sym_call] = "call",
  [sym__arg_list] = "_arg_list",
  [sym_arg] = "arg",
  [sym_equip_list] = "equip_list",
  [sym_equip_item] = "equip_item",
  [sym_equip] = "equip",
  [sym_ingredient] = "ingredient",
  [sym_node_ref] = "node_ref",
  [sym_sub_ref] = "sub_ref",
  [sym_path] = "path",
  [sym_remap] = "remap",
  [sym_mapping] = "mapping",
  [sym_amount] = "amount",
  [sym_annotation] = "annotation",
  [sym_timer] = "timer",
  [sym_flag] = "flag",
  [sym_link] = "link",
  [sym_menu_stmt] = "menu_stmt",
  [aux_sym_recipe_repeat1] = "recipe_repeat1",
  [aux_sym_menu_repeat1] = "menu_repeat1",
  [aux_sym_binding_repeat1] = "binding_repeat1",
  [aux_sym_output_list_repeat1] = "output_list_repeat1",
  [aux_sym__arg_list_repeat1] = "_arg_list_repeat1",
  [aux_sym_equip_list_repeat1] = "equip_list_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_remap_repeat1] = "remap_repeat1",
  [aux_sym_menu_stmt_repeat1] = "menu_stmt_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_recipe] = anon_sym_recipe,
  [anon_sym_menu] = anon_sym_menu,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_meta_value] = sym_meta_value,
  [anon_sym_basis] = anon_sym_basis,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LT_PLUS] = anon_sym_LT_PLUS,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_amount_text] = sym_amount_text,
  [sym_temp] = sym_temp,
  [sym_timer_active] = sym_timer_active,
  [sym_timer_passive] = sym_timer_passive,
  [sym_timer_unbounded] = sym_timer_unbounded,
  [sym_string] = sym_string,
  [anon_sym_AMPby] = anon_sym_AMPby,
  [anon_sym_AMPduring] = anon_sym_AMPduring,
  [anon_sym_AMPlag] = anon_sym_AMPlag,
  [sym_duration] = sym_duration,
  [sym_source_file] = sym_source_file,
  [sym_recipe] = sym_recipe,
  [sym_menu] = sym_menu,
  [sym__statement] = sym__statement,
  [sym_meta_line] = sym_meta_line,
  [sym_basis_decl] = sym_basis_decl,
  [sym_binding] = sym_binding,
  [sym_output_list] = sym_output_list,
  [sym_output] = sym_output,
  [sym__expr] = sym__expr,
  [sym_call] = sym_call,
  [sym__arg_list] = sym__arg_list,
  [sym_arg] = sym_arg,
  [sym_equip_list] = sym_equip_list,
  [sym_equip_item] = sym_equip_item,
  [sym_equip] = sym_equip,
  [sym_ingredient] = sym_ingredient,
  [sym_node_ref] = sym_node_ref,
  [sym_sub_ref] = sym_sub_ref,
  [sym_path] = sym_path,
  [sym_remap] = sym_remap,
  [sym_mapping] = sym_mapping,
  [sym_amount] = sym_amount,
  [sym_annotation] = sym_annotation,
  [sym_timer] = sym_timer,
  [sym_flag] = sym_flag,
  [sym_link] = sym_link,
  [sym_menu_stmt] = sym_menu_stmt,
  [aux_sym_recipe_repeat1] = aux_sym_recipe_repeat1,
  [aux_sym_menu_repeat1] = aux_sym_menu_repeat1,
  [aux_sym_binding_repeat1] = aux_sym_binding_repeat1,
  [aux_sym_output_list_repeat1] = aux_sym_output_list_repeat1,
  [aux_sym__arg_list_repeat1] = aux_sym__arg_list_repeat1,
  [aux_sym_equip_list_repeat1] = aux_sym_equip_list_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_remap_repeat1] = aux_sym_remap_repeat1,
  [aux_sym_menu_stmt_repeat1] = aux_sym_menu_stmt_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_recipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_menu] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_meta_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_basis] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_amount_text] = {
    .visible = true,
    .named = true,
  },
  [sym_temp] = {
    .visible = true,
    .named = true,
  },
  [sym_timer_active] = {
    .visible = true,
    .named = true,
  },
  [sym_timer_passive] = {
    .visible = true,
    .named = true,
  },
  [sym_timer_unbounded] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMPby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPduring] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPlag] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [sym_menu] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_meta_line] = {
    .visible = true,
    .named = true,
  },
  [sym_basis_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_output_list] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym__arg_list] = {
    .visible = false,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_equip_list] = {
    .visible = true,
    .named = true,
  },
  [sym_equip_item] = {
    .visible = true,
    .named = true,
  },
  [sym_equip] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient] = {
    .visible = true,
    .named = true,
  },
  [sym_node_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_sub_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_remap] = {
    .visible = true,
    .named = true,
  },
  [sym_mapping] = {
    .visible = true,
    .named = true,
  },
  [sym_amount] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_timer] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_menu_stmt] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_recipe_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_menu_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_binding_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_output_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_equip_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_remap_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_menu_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_amount = 2,
  field_anchor = 3,
  field_annotation = 4,
  field_duration = 5,
  field_equipment = 6,
  field_from = 7,
  field_key = 8,
  field_member = 9,
  field_name = 10,
  field_outputs = 11,
  field_path = 12,
  field_qualifier = 13,
  field_recipe = 14,
  field_remap = 15,
  field_target = 16,
  field_temp = 17,
  field_to = 18,
  field_value = 19,
  field_verb = 20,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_amount] = "amount",
  [field_anchor] = "anchor",
  [field_annotation] = "annotation",
  [field_duration] = "duration",
  [field_equipment] = "equipment",
  [field_from] = "from",
  [field_key] = "key",
  [field_member] = "member",
  [field_name] = "name",
  [field_outputs] = "outputs",
  [field_path] = "path",
  [field_qualifier] = "qualifier",
  [field_recipe] = "recipe",
  [field_remap] = "remap",
  [field_target] = "target",
  [field_temp] = "temp",
  [field_to] = "to",
  [field_value] = "value",
  [field_verb] = "verb",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 3},
  [11] = {.index = 17, .length = 3},
  [12] = {.index = 20, .length = 1},
  [13] = {.index = 21, .length = 1},
  [14] = {.index = 22, .length = 2},
  [15] = {.index = 24, .length = 2},
  [16] = {.index = 26, .length = 2},
  [17] = {.index = 28, .length = 2},
  [18] = {.index = 30, .length = 2},
  [19] = {.index = 32, .length = 2},
  [20] = {.index = 34, .length = 1},
  [21] = {.index = 35, .length = 1},
  [22] = {.index = 36, .length = 3},
  [23] = {.index = 39, .length = 2},
  [24] = {.index = 41, .length = 2},
  [25] = {.index = 43, .length = 3},
  [26] = {.index = 46, .length = 2},
  [27] = {.index = 48, .length = 3},
  [28] = {.index = 51, .length = 3},
  [29] = {.index = 54, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_key, 1},
  [3] =
    {field_key, 1},
    {field_value, 2},
  [5] =
    {field_outputs, 0},
    {field_value, 2},
  [7] =
    {field_alias, 0},
    {field_recipe, 2},
  [9] =
    {field_amount, 3},
    {field_name, 1},
  [11] =
    {field_amount, 2},
    {field_name, 0},
  [13] =
    {field_annotation, 0},
  [14] =
    {field_annotation, 3, .inherited = true},
    {field_outputs, 0},
    {field_value, 2},
  [17] =
    {field_alias, 0},
    {field_annotation, 3, .inherited = true},
    {field_recipe, 2},
  [20] =
    {field_path, 1},
  [21] =
    {field_verb, 0},
  [22] =
    {field_member, 2},
    {field_name, 0},
  [24] =
    {field_annotation, 0, .inherited = true},
    {field_annotation, 1, .inherited = true},
  [26] =
    {field_path, 1},
    {field_remap, 3},
  [28] =
    {field_anchor, 3},
    {field_path, 1},
  [30] =
    {field_equipment, 3},
    {field_verb, 0},
  [32] =
    {field_name, 1},
    {field_temp, 2},
  [34] =
    {field_target, 2},
  [35] =
    {field_duration, 2},
  [36] =
    {field_anchor, 3},
    {field_path, 1},
    {field_remap, 5},
  [39] =
    {field_amount, 4},
    {field_path, 1},
  [41] =
    {field_equipment, 4},
    {field_verb, 0},
  [43] =
    {field_amount, 4},
    {field_path, 1},
    {field_remap, 6},
  [46] =
    {field_from, 0},
    {field_to, 2},
  [48] =
    {field_amount, 2},
    {field_name, 0},
    {field_qualifier, 4},
  [51] =
    {field_amount, 6},
    {field_anchor, 3},
    {field_path, 1},
  [54] =
    {field_amount, 6},
    {field_anchor, 3},
    {field_path, 1},
    {field_remap, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 44,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 118,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '!', 52,
        '"', 1,
        '#', 55,
        '&', 14,
        '(', 49,
        ')', 51,
        ',', 46,
        '-', 11,
        '.', 53,
        '/', 57,
        '0', 71,
        ':', 39,
        ';', 50,
        '<', 2,
        '=', 45,
        '>', 56,
        '@', 26,
        '[', 47,
        ']', 48,
        '{', 22,
        '~', 12,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '+') ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(10);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(61);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(58);
      END_STATE();
    case 12:
      if (lookahead == '?') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead == 'd') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(68);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'y') ADVANCE(67);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 34:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(35);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == ':') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_meta_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LT_PLUS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_amount_text);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_amount_text);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_amount_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_temp);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_timer_active);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_timer_passive);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_timer_unbounded);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_AMPby);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_AMPduring);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_AMPlag);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'm') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_menu);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_basis);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_recipe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 35},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 35},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 10},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 10},
  [81] = {.lex_state = 10},
  [82] = {.lex_state = 10},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 10},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_recipe] = ACTIONS(1),
    [anon_sym_menu] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_basis] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT_PLUS] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_temp] = ACTIONS(1),
    [sym_timer_active] = ACTIONS(1),
    [sym_timer_passive] = ACTIONS(1),
    [sym_timer_unbounded] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_AMPby] = ACTIONS(1),
    [anon_sym_AMPduring] = ACTIONS(1),
    [anon_sym_AMPlag] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym_recipe] = STATE(97),
    [sym_menu] = STATE(97),
    [anon_sym_recipe] = ACTIONS(5),
    [anon_sym_menu] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_AMPlag,
    STATE(2), 1,
      aux_sym_binding_repeat1,
    STATE(17), 1,
      sym_annotation,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
    ACTIONS(11), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(16), 2,
      sym_temp,
      sym_string,
    ACTIONS(22), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(19), 3,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
    STATE(16), 3,
      sym_timer,
      sym_flag,
      sym_link,
  [42] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_AMPlag,
    STATE(4), 1,
      aux_sym_binding_repeat1,
    STATE(17), 1,
      sym_annotation,
    ACTIONS(28), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
    ACTIONS(30), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(34), 2,
      sym_temp,
      sym_string,
    ACTIONS(38), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(36), 3,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
    STATE(16), 3,
      sym_timer,
      sym_flag,
      sym_link,
  [84] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_AMPlag,
    STATE(2), 1,
      aux_sym_binding_repeat1,
    STATE(17), 1,
      sym_annotation,
    ACTIONS(34), 2,
      sym_temp,
      sym_string,
    ACTIONS(38), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
    ACTIONS(44), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(36), 3,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
    STATE(16), 3,
      sym_timer,
      sym_flag,
      sym_link,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(46), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(50), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [174] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(54), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [198] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(58), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(62), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [246] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_remap,
    ACTIONS(68), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(66), 10,
      ts_builtin_sym_end,
      anon_sym_COLON,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [275] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_DOT,
    ACTIONS(76), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(74), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [302] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_remap,
    ACTIONS(84), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(82), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [329] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_remap,
    ACTIONS(88), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(86), 10,
      ts_builtin_sym_end,
      anon_sym_COLON,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [358] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_remap,
    ACTIONS(94), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(92), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(96), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(100), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [427] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(104), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(108), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(112), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [490] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(116), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(120), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [532] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(124), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(128), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [574] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(132), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(136), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(140), 11,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [637] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_COLON,
    ACTIONS(150), 1,
      anon_sym_basis,
    STATE(66), 1,
      sym_output,
    STATE(114), 1,
      sym_output_list,
    STATE(29), 5,
      sym__statement,
      sym_meta_line,
      sym_basis_decl,
      sym_binding,
      aux_sym_recipe_repeat1,
  [666] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(157), 1,
      anon_sym_COLON,
    ACTIONS(160), 1,
      anon_sym_basis,
    STATE(66), 1,
      sym_output,
    STATE(114), 1,
      sym_output_list,
    STATE(28), 5,
      sym__statement,
      sym_meta_line,
      sym_basis_decl,
      sym_binding,
      aux_sym_recipe_repeat1,
  [695] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_COLON,
    ACTIONS(150), 1,
      anon_sym_basis,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    STATE(66), 1,
      sym_output,
    STATE(114), 1,
      sym_output_list,
    STATE(28), 5,
      sym__statement,
      sym_meta_line,
      sym_basis_decl,
      sym_binding,
      aux_sym_recipe_repeat1,
  [724] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_SEMI,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(171), 1,
      anon_sym_BANG,
    STATE(52), 1,
      sym_arg,
    STATE(78), 1,
      sym__arg_list,
    STATE(62), 4,
      sym_call,
      sym_equip,
      sym_ingredient,
      sym_node_ref,
  [752] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_AMPlag,
    STATE(33), 1,
      aux_sym_menu_stmt_repeat1,
    STATE(37), 1,
      sym_link,
    ACTIONS(38), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      anon_sym_COLON,
      sym_identifier,
  [774] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_AMPlag,
    STATE(31), 1,
      aux_sym_menu_stmt_repeat1,
    STATE(37), 1,
      sym_link,
    ACTIONS(38), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      anon_sym_COLON,
      sym_identifier,
  [796] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_AMPlag,
    STATE(33), 1,
      aux_sym_menu_stmt_repeat1,
    STATE(37), 1,
      sym_link,
    ACTIONS(179), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_COLON,
      sym_identifier,
  [818] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_BANG,
    STATE(69), 1,
      sym_arg,
    STATE(62), 4,
      sym_call,
      sym_equip,
      sym_ingredient,
      sym_node_ref,
  [837] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_COLON,
    STATE(38), 3,
      sym_meta_line,
      sym_menu_stmt,
      aux_sym_menu_repeat1,
  [855] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_BANG,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(59), 1,
      sym_equip_item,
    STATE(120), 1,
      sym_equip_list,
    STATE(75), 2,
      sym_equip,
      sym_node_ref,
  [875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 6,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
      sym_identifier,
  [887] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_COLON,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    STATE(40), 3,
      sym_meta_line,
      sym_menu_stmt,
      aux_sym_menu_repeat1,
  [905] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    ACTIONS(199), 1,
      anon_sym_LT_PLUS,
    STATE(3), 4,
      sym__expr,
      sym_call,
      sym_node_ref,
      sym_sub_ref,
  [921] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_COLON,
    STATE(40), 3,
      sym_meta_line,
      sym_menu_stmt,
      aux_sym_menu_repeat1,
  [939] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_DOT,
    ACTIONS(209), 1,
      anon_sym_LBRACK,
    ACTIONS(74), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [957] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_BANG,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(59), 1,
      sym_equip_item,
    STATE(92), 1,
      sym_equip_list,
    STATE(75), 2,
      sym_equip,
      sym_node_ref,
  [977] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(211), 3,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_RBRACK,
  [990] = 4,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym_meta_value,
    ACTIONS(217), 3,
      anon_sym_COLON,
      anon_sym_basis,
      sym_identifier,
  [1005] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_BANG,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(85), 1,
      sym_equip_item,
    STATE(75), 2,
      sym_equip,
      sym_node_ref,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym_temp,
    ACTIONS(223), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1034] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
    ACTIONS(229), 2,
      anon_sym_basis,
      sym_identifier,
  [1046] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      aux_sym_path_repeat1,
    ACTIONS(231), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1060] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      aux_sym_path_repeat1,
    ACTIONS(235), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1074] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym__arg_list_repeat1,
    ACTIONS(242), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1088] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_SLASH,
    STATE(48), 1,
      aux_sym_path_repeat1,
    ACTIONS(244), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1102] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym__arg_list_repeat1,
    ACTIONS(246), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1116] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_string,
    ACTIONS(248), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym__arg_list_repeat1,
    ACTIONS(255), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1142] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      ts_builtin_sym_end,
      anon_sym_COLON,
    ACTIONS(259), 2,
      anon_sym_basis,
      sym_identifier,
  [1154] = 4,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym_meta_value,
    ACTIONS(217), 2,
      anon_sym_COLON,
      sym_identifier,
  [1168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_DOT,
    ACTIONS(74), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1179] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_SLASH,
    ACTIONS(235), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1190] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_equip_list_repeat1,
  [1203] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_EQ,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_output_list_repeat1,
  [1216] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_LT_PLUS,
    ACTIONS(271), 1,
      sym_identifier,
    STATE(32), 1,
      sym_sub_ref,
  [1229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1238] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_remap_repeat1,
  [1251] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_LBRACK,
    ACTIONS(279), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1262] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1271] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_EQ,
    STATE(60), 1,
      aux_sym_output_list_repeat1,
  [1284] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_equip_list_repeat1,
  [1297] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_equip_list_repeat1,
  [1310] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1319] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_EQ,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_output_list_repeat1,
  [1332] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_remap_repeat1,
  [1345] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_remap_repeat1,
  [1358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1375] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1383] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_POUND,
    ACTIONS(314), 1,
      anon_sym_GT,
  [1393] = 3,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_amount_text,
    STATE(94), 1,
      sym_amount,
  [1403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_SEMI,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
  [1413] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_identifier,
    STATE(102), 1,
      sym_node_ref,
  [1423] = 3,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_amount_text,
    STATE(101), 1,
      sym_amount,
  [1433] = 3,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_amount_text,
    STATE(55), 1,
      sym_amount,
  [1443] = 3,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_amount_text,
    STATE(111), 1,
      sym_amount,
  [1453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
    STATE(76), 1,
      sym_path,
  [1463] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_identifier,
    STATE(88), 1,
      sym_mapping,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1505] = 3,
    ACTIONS(219), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_amount_text,
    STATE(112), 1,
      sym_amount,
  [1515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_identifier,
    STATE(63), 1,
      sym_mapping,
  [1525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      sym_identifier,
    STATE(86), 1,
      sym_output,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_RPAREN,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
  [1549] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_RBRACK,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      sym_identifier,
  [1563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_duration,
  [1570] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      ts_builtin_sym_end,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      sym_identifier,
  [1584] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym_identifier,
  [1591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_LPAREN,
  [1598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_RBRACK,
  [1605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      anon_sym_RPAREN,
  [1612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym_identifier,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      anon_sym_RPAREN,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_identifier,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_EQ,
  [1640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      sym_identifier,
  [1647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      sym_identifier,
  [1654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      anon_sym_GT,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      sym_identifier,
  [1668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_RBRACK,
  [1675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_RBRACK,
  [1682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      anon_sym_DASH_GT,
  [1689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_EQ,
  [1696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
  [1703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      anon_sym_EQ,
  [1710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      anon_sym_RBRACK,
  [1717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identifier,
  [1724] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_identifier,
  [1731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      anon_sym_RPAREN,
  [1738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 198,
  [SMALL_STATE(9)] = 222,
  [SMALL_STATE(10)] = 246,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 302,
  [SMALL_STATE(13)] = 329,
  [SMALL_STATE(14)] = 358,
  [SMALL_STATE(15)] = 385,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 427,
  [SMALL_STATE(18)] = 448,
  [SMALL_STATE(19)] = 469,
  [SMALL_STATE(20)] = 490,
  [SMALL_STATE(21)] = 511,
  [SMALL_STATE(22)] = 532,
  [SMALL_STATE(23)] = 553,
  [SMALL_STATE(24)] = 574,
  [SMALL_STATE(25)] = 595,
  [SMALL_STATE(26)] = 616,
  [SMALL_STATE(27)] = 637,
  [SMALL_STATE(28)] = 666,
  [SMALL_STATE(29)] = 695,
  [SMALL_STATE(30)] = 724,
  [SMALL_STATE(31)] = 752,
  [SMALL_STATE(32)] = 774,
  [SMALL_STATE(33)] = 796,
  [SMALL_STATE(34)] = 818,
  [SMALL_STATE(35)] = 837,
  [SMALL_STATE(36)] = 855,
  [SMALL_STATE(37)] = 875,
  [SMALL_STATE(38)] = 887,
  [SMALL_STATE(39)] = 905,
  [SMALL_STATE(40)] = 921,
  [SMALL_STATE(41)] = 939,
  [SMALL_STATE(42)] = 957,
  [SMALL_STATE(43)] = 977,
  [SMALL_STATE(44)] = 990,
  [SMALL_STATE(45)] = 1005,
  [SMALL_STATE(46)] = 1022,
  [SMALL_STATE(47)] = 1034,
  [SMALL_STATE(48)] = 1046,
  [SMALL_STATE(49)] = 1060,
  [SMALL_STATE(50)] = 1074,
  [SMALL_STATE(51)] = 1088,
  [SMALL_STATE(52)] = 1102,
  [SMALL_STATE(53)] = 1116,
  [SMALL_STATE(54)] = 1128,
  [SMALL_STATE(55)] = 1142,
  [SMALL_STATE(56)] = 1154,
  [SMALL_STATE(57)] = 1168,
  [SMALL_STATE(58)] = 1179,
  [SMALL_STATE(59)] = 1190,
  [SMALL_STATE(60)] = 1203,
  [SMALL_STATE(61)] = 1216,
  [SMALL_STATE(62)] = 1229,
  [SMALL_STATE(63)] = 1238,
  [SMALL_STATE(64)] = 1251,
  [SMALL_STATE(65)] = 1262,
  [SMALL_STATE(66)] = 1271,
  [SMALL_STATE(67)] = 1284,
  [SMALL_STATE(68)] = 1297,
  [SMALL_STATE(69)] = 1310,
  [SMALL_STATE(70)] = 1319,
  [SMALL_STATE(71)] = 1332,
  [SMALL_STATE(72)] = 1345,
  [SMALL_STATE(73)] = 1358,
  [SMALL_STATE(74)] = 1367,
  [SMALL_STATE(75)] = 1375,
  [SMALL_STATE(76)] = 1383,
  [SMALL_STATE(77)] = 1393,
  [SMALL_STATE(78)] = 1403,
  [SMALL_STATE(79)] = 1413,
  [SMALL_STATE(80)] = 1423,
  [SMALL_STATE(81)] = 1433,
  [SMALL_STATE(82)] = 1443,
  [SMALL_STATE(83)] = 1453,
  [SMALL_STATE(84)] = 1463,
  [SMALL_STATE(85)] = 1473,
  [SMALL_STATE(86)] = 1481,
  [SMALL_STATE(87)] = 1489,
  [SMALL_STATE(88)] = 1497,
  [SMALL_STATE(89)] = 1505,
  [SMALL_STATE(90)] = 1515,
  [SMALL_STATE(91)] = 1525,
  [SMALL_STATE(92)] = 1535,
  [SMALL_STATE(93)] = 1542,
  [SMALL_STATE(94)] = 1549,
  [SMALL_STATE(95)] = 1556,
  [SMALL_STATE(96)] = 1563,
  [SMALL_STATE(97)] = 1570,
  [SMALL_STATE(98)] = 1577,
  [SMALL_STATE(99)] = 1584,
  [SMALL_STATE(100)] = 1591,
  [SMALL_STATE(101)] = 1598,
  [SMALL_STATE(102)] = 1605,
  [SMALL_STATE(103)] = 1612,
  [SMALL_STATE(104)] = 1619,
  [SMALL_STATE(105)] = 1626,
  [SMALL_STATE(106)] = 1633,
  [SMALL_STATE(107)] = 1640,
  [SMALL_STATE(108)] = 1647,
  [SMALL_STATE(109)] = 1654,
  [SMALL_STATE(110)] = 1661,
  [SMALL_STATE(111)] = 1668,
  [SMALL_STATE(112)] = 1675,
  [SMALL_STATE(113)] = 1682,
  [SMALL_STATE(114)] = 1689,
  [SMALL_STATE(115)] = 1696,
  [SMALL_STATE(116)] = 1703,
  [SMALL_STATE(117)] = 1710,
  [SMALL_STATE(118)] = 1717,
  [SMALL_STATE(119)] = 1724,
  [SMALL_STATE(120)] = 1731,
  [SMALL_STATE(121)] = 1738,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15), SHIFT_REPEAT(119),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15), SHIFT_REPEAT(16),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15), SHIFT_REPEAT(15),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15), SHIFT_REPEAT(93),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 15), SHIFT_REPEAT(100),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, 0, 5),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 3, 0, 5),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 4, 0, 10),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 4, 0, 10),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_ref, 3, 0, 14),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_ref, 3, 0, 14),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 13),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 13),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 13),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 13),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6, 0, 24),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 6, 0, 24),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 18),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5, 0, 18),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 3, 0, 12),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 3, 0, 12),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_ref, 1, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_ref, 1, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 6, 0, 23),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 6, 0, 23),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 5, 0, 17),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 5, 0, 17),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 8, 0, 28),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 8, 0, 28),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timer, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timer, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 1, 0, 9),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_binding_repeat1, 1, 0, 9),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 4, 0, 16),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 4, 0, 16),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 20),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 20),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 3, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag, 3, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 6, 0, 22),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 6, 0, 22),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 21),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 21),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remap, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_remap, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remap, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_remap, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 7, 0, 25),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 7, 0, 25),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 9, 0, 29),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 9, 0, 29),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 2, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 3, 0, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_stmt, 4, 0, 11),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_stmt, 3, 0, 6),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 2, 0, 15),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 2, 0, 15), SHIFT_REPEAT(93),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 2, 0, 15), SHIFT_REPEAT(100),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu, 2, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 1, 0, 9),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu, 3, 0, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_amount, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_amount, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_line, 2, 0, 3),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meta_line, 2, 0, 3),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip, 2, 0, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_line, 3, 0, 4),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meta_line, 3, 0, 4),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient, 4, 0, 8),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basis_decl, 4, 0, 7),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_basis_decl, 4, 0, 7),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip_list, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_list, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 1, 0, 2),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip, 3, 0, 19),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_list, 1, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip_list, 2, 0, 0),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_equip_list_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_equip_list_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_output_list_repeat1, 2, 0, 0),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_output_list_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [299] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_remap_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_remap_repeat1, 2, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient, 5, 0, 27),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mapping, 3, 0, 26),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip_item, 1, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 4, 0, 8),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [376] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_swede(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
