#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 118
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 28

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_recipe = 2,
  anon_sym_menu = 3,
  sym_comment = 4,
  sym_meta_text = 5,
  anon_sym_basis = 6,
  anon_sym_EQ = 7,
  anon_sym_COMMA = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LPAREN = 11,
  anon_sym_SEMI = 12,
  anon_sym_RPAREN = 13,
  anon_sym_BANG = 14,
  anon_sym_DOT = 15,
  anon_sym_LT_PLUS = 16,
  anon_sym_POUND = 17,
  anon_sym_GT = 18,
  anon_sym_SLASH = 19,
  anon_sym_DASH_GT = 20,
  sym_amount_text = 21,
  sym_temp = 22,
  sym_timer_active = 23,
  sym_timer_passive = 24,
  sym_timer_unbounded = 25,
  sym_string = 26,
  anon_sym_AMPby = 27,
  anon_sym_AMPduring = 28,
  anon_sym_AMPlag = 29,
  sym_duration = 30,
  sym_source_file = 31,
  sym_recipe = 32,
  sym_menu = 33,
  sym__statement = 34,
  sym_meta_line = 35,
  sym_basis_decl = 36,
  sym_binding = 37,
  sym_output_list = 38,
  sym_output = 39,
  sym__expr = 40,
  sym_call = 41,
  sym__arg_list = 42,
  sym_arg = 43,
  sym_equip_list = 44,
  sym_equip_item = 45,
  sym_equip = 46,
  sym_ingredient = 47,
  sym_node_ref = 48,
  sym_sub_ref = 49,
  sym_path = 50,
  sym_remap = 51,
  sym_mapping = 52,
  sym_amount = 53,
  sym_annotation = 54,
  sym_timer = 55,
  sym_flag = 56,
  sym_link = 57,
  sym_menu_stmt = 58,
  aux_sym_recipe_repeat1 = 59,
  aux_sym_menu_repeat1 = 60,
  aux_sym_binding_repeat1 = 61,
  aux_sym_output_list_repeat1 = 62,
  aux_sym__arg_list_repeat1 = 63,
  aux_sym_equip_list_repeat1 = 64,
  aux_sym_path_repeat1 = 65,
  aux_sym_remap_repeat1 = 66,
  aux_sym_menu_stmt_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_recipe] = "recipe",
  [anon_sym_menu] = "menu",
  [sym_comment] = "comment",
  [sym_meta_text] = "meta_text",
  [anon_sym_basis] = "basis",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_SEMI] = ";",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_LT_PLUS] = "<+",
  [anon_sym_POUND] = "#",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH_GT] = "->",
  [sym_amount_text] = "amount_text",
  [sym_temp] = "temp",
  [sym_timer_active] = "timer_active",
  [sym_timer_passive] = "timer_passive",
  [sym_timer_unbounded] = "timer_unbounded",
  [sym_string] = "string",
  [anon_sym_AMPby] = "&by",
  [anon_sym_AMPduring] = "&during",
  [anon_sym_AMPlag] = "&lag",
  [sym_duration] = "duration",
  [sym_source_file] = "source_file",
  [sym_recipe] = "recipe",
  [sym_menu] = "menu",
  [sym__statement] = "_statement",
  [sym_meta_line] = "meta_line",
  [sym_basis_decl] = "basis_decl",
  [sym_binding] = "binding",
  [sym_output_list] = "output_list",
  [sym_output] = "output",
  [sym__expr] = "_expr",
  [sym_call] = "call",
  [sym__arg_list] = "_arg_list",
  [sym_arg] = "arg",
  [sym_equip_list] = "equip_list",
  [sym_equip_item] = "equip_item",
  [sym_equip] = "equip",
  [sym_ingredient] = "ingredient",
  [sym_node_ref] = "node_ref",
  [sym_sub_ref] = "sub_ref",
  [sym_path] = "path",
  [sym_remap] = "remap",
  [sym_mapping] = "mapping",
  [sym_amount] = "amount",
  [sym_annotation] = "annotation",
  [sym_timer] = "timer",
  [sym_flag] = "flag",
  [sym_link] = "link",
  [sym_menu_stmt] = "menu_stmt",
  [aux_sym_recipe_repeat1] = "recipe_repeat1",
  [aux_sym_menu_repeat1] = "menu_repeat1",
  [aux_sym_binding_repeat1] = "binding_repeat1",
  [aux_sym_output_list_repeat1] = "output_list_repeat1",
  [aux_sym__arg_list_repeat1] = "_arg_list_repeat1",
  [aux_sym_equip_list_repeat1] = "equip_list_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_remap_repeat1] = "remap_repeat1",
  [aux_sym_menu_stmt_repeat1] = "menu_stmt_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_recipe] = anon_sym_recipe,
  [anon_sym_menu] = anon_sym_menu,
  [sym_comment] = sym_comment,
  [sym_meta_text] = sym_meta_text,
  [anon_sym_basis] = anon_sym_basis,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LT_PLUS] = anon_sym_LT_PLUS,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_amount_text] = sym_amount_text,
  [sym_temp] = sym_temp,
  [sym_timer_active] = sym_timer_active,
  [sym_timer_passive] = sym_timer_passive,
  [sym_timer_unbounded] = sym_timer_unbounded,
  [sym_string] = sym_string,
  [anon_sym_AMPby] = anon_sym_AMPby,
  [anon_sym_AMPduring] = anon_sym_AMPduring,
  [anon_sym_AMPlag] = anon_sym_AMPlag,
  [sym_duration] = sym_duration,
  [sym_source_file] = sym_source_file,
  [sym_recipe] = sym_recipe,
  [sym_menu] = sym_menu,
  [sym__statement] = sym__statement,
  [sym_meta_line] = sym_meta_line,
  [sym_basis_decl] = sym_basis_decl,
  [sym_binding] = sym_binding,
  [sym_output_list] = sym_output_list,
  [sym_output] = sym_output,
  [sym__expr] = sym__expr,
  [sym_call] = sym_call,
  [sym__arg_list] = sym__arg_list,
  [sym_arg] = sym_arg,
  [sym_equip_list] = sym_equip_list,
  [sym_equip_item] = sym_equip_item,
  [sym_equip] = sym_equip,
  [sym_ingredient] = sym_ingredient,
  [sym_node_ref] = sym_node_ref,
  [sym_sub_ref] = sym_sub_ref,
  [sym_path] = sym_path,
  [sym_remap] = sym_remap,
  [sym_mapping] = sym_mapping,
  [sym_amount] = sym_amount,
  [sym_annotation] = sym_annotation,
  [sym_timer] = sym_timer,
  [sym_flag] = sym_flag,
  [sym_link] = sym_link,
  [sym_menu_stmt] = sym_menu_stmt,
  [aux_sym_recipe_repeat1] = aux_sym_recipe_repeat1,
  [aux_sym_menu_repeat1] = aux_sym_menu_repeat1,
  [aux_sym_binding_repeat1] = aux_sym_binding_repeat1,
  [aux_sym_output_list_repeat1] = aux_sym_output_list_repeat1,
  [aux_sym__arg_list_repeat1] = aux_sym__arg_list_repeat1,
  [aux_sym_equip_list_repeat1] = aux_sym_equip_list_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_remap_repeat1] = aux_sym_remap_repeat1,
  [aux_sym_menu_stmt_repeat1] = aux_sym_menu_stmt_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_recipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_menu] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_basis] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_amount_text] = {
    .visible = true,
    .named = true,
  },
  [sym_temp] = {
    .visible = true,
    .named = true,
  },
  [sym_timer_active] = {
    .visible = true,
    .named = true,
  },
  [sym_timer_passive] = {
    .visible = true,
    .named = true,
  },
  [sym_timer_unbounded] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMPby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPduring] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMPlag] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [sym_menu] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_meta_line] = {
    .visible = true,
    .named = true,
  },
  [sym_basis_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_output_list] = {
    .visible = true,
    .named = true,
  },
  [sym_output] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym__arg_list] = {
    .visible = false,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_equip_list] = {
    .visible = true,
    .named = true,
  },
  [sym_equip_item] = {
    .visible = true,
    .named = true,
  },
  [sym_equip] = {
    .visible = true,
    .named = true,
  },
  [sym_ingredient] = {
    .visible = true,
    .named = true,
  },
  [sym_node_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_sub_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_remap] = {
    .visible = true,
    .named = true,
  },
  [sym_mapping] = {
    .visible = true,
    .named = true,
  },
  [sym_amount] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_timer] = {
    .visible = true,
    .named = true,
  },
  [sym_flag] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_menu_stmt] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_recipe_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_menu_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_binding_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_output_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_equip_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_remap_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_menu_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_amount = 2,
  field_anchor = 3,
  field_annotation = 4,
  field_duration = 5,
  field_equipment = 6,
  field_from = 7,
  field_member = 8,
  field_name = 9,
  field_outputs = 10,
  field_path = 11,
  field_qualifier = 12,
  field_recipe = 13,
  field_remap = 14,
  field_target = 15,
  field_temp = 16,
  field_to = 17,
  field_value = 18,
  field_verb = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_amount] = "amount",
  [field_anchor] = "anchor",
  [field_annotation] = "annotation",
  [field_duration] = "duration",
  [field_equipment] = "equipment",
  [field_from] = "from",
  [field_member] = "member",
  [field_name] = "name",
  [field_outputs] = "outputs",
  [field_path] = "path",
  [field_qualifier] = "qualifier",
  [field_recipe] = "recipe",
  [field_remap] = "remap",
  [field_target] = "target",
  [field_temp] = "temp",
  [field_to] = "to",
  [field_value] = "value",
  [field_verb] = "verb",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 3},
  [10] = {.index = 17, .length = 1},
  [11] = {.index = 18, .length = 1},
  [12] = {.index = 19, .length = 2},
  [13] = {.index = 21, .length = 2},
  [14] = {.index = 23, .length = 2},
  [15] = {.index = 25, .length = 2},
  [16] = {.index = 27, .length = 2},
  [17] = {.index = 29, .length = 2},
  [18] = {.index = 31, .length = 1},
  [19] = {.index = 32, .length = 1},
  [20] = {.index = 33, .length = 3},
  [21] = {.index = 36, .length = 2},
  [22] = {.index = 38, .length = 2},
  [23] = {.index = 40, .length = 3},
  [24] = {.index = 43, .length = 2},
  [25] = {.index = 45, .length = 3},
  [26] = {.index = 48, .length = 3},
  [27] = {.index = 51, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_outputs, 0},
    {field_value, 2},
  [4] =
    {field_alias, 0},
    {field_recipe, 2},
  [6] =
    {field_amount, 3},
    {field_name, 1},
  [8] =
    {field_amount, 2},
    {field_name, 0},
  [10] =
    {field_annotation, 0},
  [11] =
    {field_annotation, 3, .inherited = true},
    {field_outputs, 0},
    {field_value, 2},
  [14] =
    {field_alias, 0},
    {field_annotation, 3, .inherited = true},
    {field_recipe, 2},
  [17] =
    {field_path, 1},
  [18] =
    {field_verb, 0},
  [19] =
    {field_member, 2},
    {field_name, 0},
  [21] =
    {field_annotation, 0, .inherited = true},
    {field_annotation, 1, .inherited = true},
  [23] =
    {field_path, 1},
    {field_remap, 3},
  [25] =
    {field_anchor, 3},
    {field_path, 1},
  [27] =
    {field_equipment, 3},
    {field_verb, 0},
  [29] =
    {field_name, 1},
    {field_temp, 2},
  [31] =
    {field_target, 2},
  [32] =
    {field_duration, 2},
  [33] =
    {field_anchor, 3},
    {field_path, 1},
    {field_remap, 5},
  [36] =
    {field_amount, 4},
    {field_path, 1},
  [38] =
    {field_equipment, 4},
    {field_verb, 0},
  [40] =
    {field_amount, 4},
    {field_path, 1},
    {field_remap, 6},
  [43] =
    {field_from, 0},
    {field_to, 2},
  [45] =
    {field_amount, 2},
    {field_name, 0},
    {field_qualifier, 4},
  [48] =
    {field_amount, 6},
    {field_anchor, 3},
    {field_path, 1},
  [51] =
    {field_amount, 6},
    {field_anchor, 3},
    {field_path, 1},
    {field_remap, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '!', 48,
        '"', 1,
        '#', 51,
        '&', 14,
        '(', 45,
        ')', 47,
        ',', 42,
        '-', 11,
        '.', 49,
        '/', 53,
        '0', 67,
        ':', 34,
        ';', 46,
        '<', 2,
        '=', 41,
        '>', 52,
        '@', 26,
        '[', 43,
        ']', 44,
        '{', 22,
        '~', 12,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '+') ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(10);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(54);
      END_STATE();
    case 12:
      if (lookahead == '?') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead == 'd') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(65);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'y') ADVANCE(63);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 34:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == ']') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_meta_text);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_meta_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_PLUS);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_amount_text);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_amount_text);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_amount_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_temp);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_timer_active);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_timer_passive);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_timer_unbounded);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_AMPby);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_AMPduring);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_AMPlag);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_duration);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == 'd' ||
          lookahead == 'h' ||
          lookahead == 'm' ||
          lookahead == 's') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'm') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_menu);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_basis);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_recipe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 10},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 10},
  [83] = {.lex_state = 10},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 10},
  [88] = {.lex_state = 10},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_recipe] = ACTIONS(1),
    [anon_sym_menu] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_meta_text] = ACTIONS(1),
    [anon_sym_basis] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LT_PLUS] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_temp] = ACTIONS(1),
    [sym_timer_active] = ACTIONS(1),
    [sym_timer_passive] = ACTIONS(1),
    [sym_timer_unbounded] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_AMPby] = ACTIONS(1),
    [anon_sym_AMPduring] = ACTIONS(1),
    [anon_sym_AMPlag] = ACTIONS(1),
    [sym_duration] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(97),
    [sym_recipe] = STATE(95),
    [sym_menu] = STATE(95),
    [anon_sym_recipe] = ACTIONS(5),
    [anon_sym_menu] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_AMPlag,
    STATE(4), 1,
      aux_sym_binding_repeat1,
    STATE(18), 1,
      sym_annotation,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      sym_meta_text,
    ACTIONS(11), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(15), 2,
      sym_temp,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(17), 3,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
    STATE(15), 3,
      sym_timer,
      sym_flag,
      sym_link,
  [42] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_AMPlag,
    STATE(3), 1,
      aux_sym_binding_repeat1,
    STATE(18), 1,
      sym_annotation,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      sym_meta_text,
    ACTIONS(25), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(30), 2,
      sym_temp,
      sym_string,
    ACTIONS(36), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(33), 3,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
    STATE(15), 3,
      sym_timer,
      sym_flag,
      sym_link,
  [84] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_AMPlag,
    STATE(3), 1,
      aux_sym_binding_repeat1,
    STATE(18), 1,
      sym_annotation,
    ACTIONS(15), 2,
      sym_temp,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      sym_meta_text,
    ACTIONS(44), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(17), 3,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
    STATE(15), 3,
      sym_timer,
      sym_flag,
      sym_link,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(46), 14,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(50), 14,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [174] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(54), 14,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [198] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(58), 14,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(62), 14,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [246] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      sym_remap,
    ACTIONS(68), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(66), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [273] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_remap,
    ACTIONS(74), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(72), 10,
      ts_builtin_sym_end,
      sym_meta_text,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [302] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym_remap,
    ACTIONS(80), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(78), 10,
      ts_builtin_sym_end,
      sym_meta_text,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [331] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_DOT,
    ACTIONS(86), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(84), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [358] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_remap,
    ACTIONS(94), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(92), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(96), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(100), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [427] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(104), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(108), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(112), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [490] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(116), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(120), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [532] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(124), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(128), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [574] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(132), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(136), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(140), 11,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_LBRACK,
      sym_temp,
      sym_timer_active,
      sym_timer_passive,
      sym_timer_unbounded,
      sym_string,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
  [637] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      sym_meta_text,
    ACTIONS(150), 1,
      anon_sym_basis,
    STATE(56), 1,
      sym_output,
    STATE(108), 1,
      sym_output_list,
    STATE(28), 5,
      sym__statement,
      sym_meta_line,
      sym_basis_decl,
      sym_binding,
      aux_sym_recipe_repeat1,
  [666] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(157), 1,
      sym_meta_text,
    ACTIONS(160), 1,
      anon_sym_basis,
    STATE(56), 1,
      sym_output,
    STATE(108), 1,
      sym_output_list,
    STATE(28), 5,
      sym__statement,
      sym_meta_line,
      sym_basis_decl,
      sym_binding,
      aux_sym_recipe_repeat1,
  [695] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      sym_meta_text,
    ACTIONS(150), 1,
      anon_sym_basis,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_output,
    STATE(108), 1,
      sym_output_list,
    STATE(27), 5,
      sym__statement,
      sym_meta_line,
      sym_basis_decl,
      sym_binding,
      aux_sym_recipe_repeat1,
  [724] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_SEMI,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(171), 1,
      anon_sym_BANG,
    STATE(53), 1,
      sym_arg,
    STATE(72), 1,
      sym__arg_list,
    STATE(55), 4,
      sym_call,
      sym_equip,
      sym_ingredient,
      sym_node_ref,
  [752] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_AMPlag,
    STATE(31), 1,
      aux_sym_menu_stmt_repeat1,
    STATE(39), 1,
      sym_link,
    ACTIONS(175), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(173), 3,
      ts_builtin_sym_end,
      sym_meta_text,
      sym_identifier,
  [774] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_AMPlag,
    STATE(33), 1,
      aux_sym_menu_stmt_repeat1,
    STATE(39), 1,
      sym_link,
    ACTIONS(19), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(181), 3,
      ts_builtin_sym_end,
      sym_meta_text,
      sym_identifier,
  [796] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_AMPlag,
    STATE(31), 1,
      aux_sym_menu_stmt_repeat1,
    STATE(39), 1,
      sym_link,
    ACTIONS(19), 2,
      anon_sym_AMPby,
      anon_sym_AMPduring,
    ACTIONS(183), 3,
      ts_builtin_sym_end,
      sym_meta_text,
      sym_identifier,
  [818] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_BANG,
    STATE(63), 1,
      sym_arg,
    STATE(55), 4,
      sym_call,
      sym_equip,
      sym_ingredient,
      sym_node_ref,
  [837] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_BANG,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(60), 1,
      sym_equip_item,
    STATE(112), 1,
      sym_equip_list,
    STATE(80), 2,
      sym_equip,
      sym_node_ref,
  [857] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_LT_PLUS,
    STATE(2), 4,
      sym__expr,
      sym_call,
      sym_node_ref,
      sym_sub_ref,
  [873] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_DOT,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    ACTIONS(84), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [891] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 1,
      sym_identifier,
    ACTIONS(198), 1,
      sym_meta_text,
    STATE(38), 3,
      sym_meta_line,
      sym_menu_stmt,
      aux_sym_menu_repeat1,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 6,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_AMPby,
      anon_sym_AMPduring,
      anon_sym_AMPlag,
      sym_identifier,
  [921] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_meta_text,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 1,
      sym_identifier,
    STATE(38), 3,
      sym_meta_line,
      sym_menu_stmt,
      aux_sym_menu_repeat1,
  [939] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_meta_text,
    ACTIONS(205), 1,
      sym_identifier,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    STATE(40), 3,
      sym_meta_line,
      sym_menu_stmt,
      aux_sym_menu_repeat1,
  [957] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_BANG,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(60), 1,
      sym_equip_item,
    STATE(93), 1,
      sym_equip_list,
    STATE(80), 2,
      sym_equip,
      sym_node_ref,
  [977] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_BANG,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(81), 1,
      sym_equip_item,
    STATE(80), 2,
      sym_equip,
      sym_node_ref,
  [994] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_basis,
      sym_identifier,
    ACTIONS(209), 3,
      ts_builtin_sym_end,
      sym_meta_text,
      anon_sym_RBRACK,
  [1007] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      sym_meta_text,
    ACTIONS(215), 2,
      anon_sym_basis,
      sym_identifier,
  [1019] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_SLASH,
    STATE(52), 1,
      aux_sym_path_repeat1,
    ACTIONS(217), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym__arg_list_repeat1,
    ACTIONS(223), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1047] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      ts_builtin_sym_end,
      sym_meta_text,
    ACTIONS(227), 2,
      anon_sym_basis,
      sym_identifier,
  [1059] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym__arg_list_repeat1,
    ACTIONS(232), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1073] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_SLASH,
    STATE(46), 1,
      aux_sym_path_repeat1,
    ACTIONS(234), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1087] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_string,
    ACTIONS(236), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1099] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_SLASH,
    STATE(52), 1,
      aux_sym_path_repeat1,
    ACTIONS(240), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1113] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym__arg_list_repeat1,
    ACTIONS(245), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1127] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_temp,
    ACTIONS(247), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1148] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_EQ,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      aux_sym_output_list_repeat1,
  [1161] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_EQ,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_output_list_repeat1,
  [1174] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_SLASH,
    ACTIONS(240), 2,
      anon_sym_POUND,
      anon_sym_GT,
  [1185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_DOT,
    ACTIONS(84), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1196] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_equip_list_repeat1,
  [1209] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_remap_repeat1,
  [1222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1231] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1240] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_EQ,
    STATE(57), 1,
      aux_sym_output_list_repeat1,
  [1253] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LT_PLUS,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(32), 1,
      sym_sub_ref,
  [1266] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_remap_repeat1,
  [1279] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_equip_list_repeat1,
  [1292] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LBRACK,
    ACTIONS(285), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1303] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_remap_repeat1,
  [1316] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1325] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_equip_list_repeat1,
  [1338] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_SEMI,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
  [1348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
    STATE(61), 1,
      sym_mapping,
  [1358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1366] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      sym_identifier,
    STATE(76), 1,
      sym_output,
  [1376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1384] = 3,
    ACTIONS(308), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_amount_text,
    STATE(109), 1,
      sym_amount,
  [1394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(105), 1,
      sym_node_ref,
  [1404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
    STATE(86), 1,
      sym_mapping,
  [1414] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1422] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1430] = 3,
    ACTIONS(308), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_amount_text,
    STATE(92), 1,
      sym_amount,
  [1440] = 3,
    ACTIONS(308), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_amount_text,
    STATE(45), 1,
      sym_amount,
  [1450] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_POUND,
    ACTIONS(316), 1,
      anon_sym_GT,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1476] = 3,
    ACTIONS(308), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_amount_text,
    STATE(113), 1,
      sym_amount,
  [1486] = 3,
    ACTIONS(308), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_amount_text,
    STATE(110), 1,
      sym_amount,
  [1496] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym_identifier,
    STATE(84), 1,
      sym_path,
  [1506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_identifier,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_RBRACK,
  [1520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_RBRACK,
  [1527] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
  [1534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      sym_identifier,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      ts_builtin_sym_end,
  [1548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_duration,
  [1555] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      ts_builtin_sym_end,
  [1562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      anon_sym_EQ,
  [1569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_identifier,
  [1576] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      sym_identifier,
  [1583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym_identifier,
  [1590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym_identifier,
  [1597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      sym_identifier,
  [1604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      anon_sym_EQ,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_RPAREN,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      anon_sym_RPAREN,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_identifier,
  [1632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_EQ,
  [1639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_RBRACK,
  [1646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_RBRACK,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      anon_sym_DASH_GT,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
  [1667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_RBRACK,
  [1674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
  [1681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      anon_sym_LPAREN,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      sym_identifier,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 198,
  [SMALL_STATE(9)] = 222,
  [SMALL_STATE(10)] = 246,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 302,
  [SMALL_STATE(13)] = 331,
  [SMALL_STATE(14)] = 358,
  [SMALL_STATE(15)] = 385,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 427,
  [SMALL_STATE(18)] = 448,
  [SMALL_STATE(19)] = 469,
  [SMALL_STATE(20)] = 490,
  [SMALL_STATE(21)] = 511,
  [SMALL_STATE(22)] = 532,
  [SMALL_STATE(23)] = 553,
  [SMALL_STATE(24)] = 574,
  [SMALL_STATE(25)] = 595,
  [SMALL_STATE(26)] = 616,
  [SMALL_STATE(27)] = 637,
  [SMALL_STATE(28)] = 666,
  [SMALL_STATE(29)] = 695,
  [SMALL_STATE(30)] = 724,
  [SMALL_STATE(31)] = 752,
  [SMALL_STATE(32)] = 774,
  [SMALL_STATE(33)] = 796,
  [SMALL_STATE(34)] = 818,
  [SMALL_STATE(35)] = 837,
  [SMALL_STATE(36)] = 857,
  [SMALL_STATE(37)] = 873,
  [SMALL_STATE(38)] = 891,
  [SMALL_STATE(39)] = 909,
  [SMALL_STATE(40)] = 921,
  [SMALL_STATE(41)] = 939,
  [SMALL_STATE(42)] = 957,
  [SMALL_STATE(43)] = 977,
  [SMALL_STATE(44)] = 994,
  [SMALL_STATE(45)] = 1007,
  [SMALL_STATE(46)] = 1019,
  [SMALL_STATE(47)] = 1033,
  [SMALL_STATE(48)] = 1047,
  [SMALL_STATE(49)] = 1059,
  [SMALL_STATE(50)] = 1073,
  [SMALL_STATE(51)] = 1087,
  [SMALL_STATE(52)] = 1099,
  [SMALL_STATE(53)] = 1113,
  [SMALL_STATE(54)] = 1127,
  [SMALL_STATE(55)] = 1139,
  [SMALL_STATE(56)] = 1148,
  [SMALL_STATE(57)] = 1161,
  [SMALL_STATE(58)] = 1174,
  [SMALL_STATE(59)] = 1185,
  [SMALL_STATE(60)] = 1196,
  [SMALL_STATE(61)] = 1209,
  [SMALL_STATE(62)] = 1222,
  [SMALL_STATE(63)] = 1231,
  [SMALL_STATE(64)] = 1240,
  [SMALL_STATE(65)] = 1253,
  [SMALL_STATE(66)] = 1266,
  [SMALL_STATE(67)] = 1279,
  [SMALL_STATE(68)] = 1292,
  [SMALL_STATE(69)] = 1303,
  [SMALL_STATE(70)] = 1316,
  [SMALL_STATE(71)] = 1325,
  [SMALL_STATE(72)] = 1338,
  [SMALL_STATE(73)] = 1348,
  [SMALL_STATE(74)] = 1358,
  [SMALL_STATE(75)] = 1366,
  [SMALL_STATE(76)] = 1376,
  [SMALL_STATE(77)] = 1384,
  [SMALL_STATE(78)] = 1394,
  [SMALL_STATE(79)] = 1404,
  [SMALL_STATE(80)] = 1414,
  [SMALL_STATE(81)] = 1422,
  [SMALL_STATE(82)] = 1430,
  [SMALL_STATE(83)] = 1440,
  [SMALL_STATE(84)] = 1450,
  [SMALL_STATE(85)] = 1460,
  [SMALL_STATE(86)] = 1468,
  [SMALL_STATE(87)] = 1476,
  [SMALL_STATE(88)] = 1486,
  [SMALL_STATE(89)] = 1496,
  [SMALL_STATE(90)] = 1506,
  [SMALL_STATE(91)] = 1513,
  [SMALL_STATE(92)] = 1520,
  [SMALL_STATE(93)] = 1527,
  [SMALL_STATE(94)] = 1534,
  [SMALL_STATE(95)] = 1541,
  [SMALL_STATE(96)] = 1548,
  [SMALL_STATE(97)] = 1555,
  [SMALL_STATE(98)] = 1562,
  [SMALL_STATE(99)] = 1569,
  [SMALL_STATE(100)] = 1576,
  [SMALL_STATE(101)] = 1583,
  [SMALL_STATE(102)] = 1590,
  [SMALL_STATE(103)] = 1597,
  [SMALL_STATE(104)] = 1604,
  [SMALL_STATE(105)] = 1611,
  [SMALL_STATE(106)] = 1618,
  [SMALL_STATE(107)] = 1625,
  [SMALL_STATE(108)] = 1632,
  [SMALL_STATE(109)] = 1639,
  [SMALL_STATE(110)] = 1646,
  [SMALL_STATE(111)] = 1653,
  [SMALL_STATE(112)] = 1660,
  [SMALL_STATE(113)] = 1667,
  [SMALL_STATE(114)] = 1674,
  [SMALL_STATE(115)] = 1681,
  [SMALL_STATE(116)] = 1688,
  [SMALL_STATE(117)] = 1695,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, 0, 3),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 3, 0, 3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13), SHIFT_REPEAT(102),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13), SHIFT_REPEAT(15),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13), SHIFT_REPEAT(17),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13), SHIFT_REPEAT(114),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 2, 0, 13), SHIFT_REPEAT(115),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 4, 0, 8),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 4, 0, 8),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6, 0, 22),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 6, 0, 22),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_ref, 3, 0, 12),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_ref, 3, 0, 12),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 11),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 11),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 11),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 11),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 16),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5, 0, 16),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 6, 0, 21),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 6, 0, 21),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 3, 0, 10),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 3, 0, 10),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 5, 0, 15),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 5, 0, 15),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_ref, 1, 0, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_ref, 1, 0, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 8, 0, 26),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 8, 0, 26),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 4, 0, 14),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 4, 0, 14),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timer, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timer, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_binding_repeat1, 1, 0, 7),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_binding_repeat1, 1, 0, 7),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flag, 3, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flag, 3, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 18),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 18),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 4, 0, 19),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 4, 0, 19),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 6, 0, 20),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 6, 0, 20),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remap, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_remap, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 7, 0, 23),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 7, 0, 23),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remap, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_remap, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sub_ref, 9, 0, 27),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sub_ref, 9, 0, 27),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 3, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 2, 0, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 2, 0, 13),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 2, 0, 13), SHIFT_REPEAT(114),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 2, 0, 13), SHIFT_REPEAT(115),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_stmt, 3, 0, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_stmt, 4, 0, 9),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_menu_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_menu_stmt_repeat1, 1, 0, 7),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu, 3, 0, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu, 2, 0, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_amount, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_amount, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basis_decl, 4, 0, 5),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_basis_decl, 4, 0, 5),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_line, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meta_line, 1, 0, 0),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arg_list_repeat1, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient, 4, 0, 6),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arg_list, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip, 2, 0, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_list, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_output_list_repeat1, 2, 0, 0),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_output_list_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip_list, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip, 3, 0, 17),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_list, 2, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_equip_list_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_equip_list_repeat1, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 1, 0, 2),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_remap_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_remap_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ingredient, 5, 0, 25),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip_list, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output, 4, 0, 6),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equip_item, 1, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mapping, 3, 0, 24),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [336] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_swede(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
